---
# Handlers pour Nginx
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: restart nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    state: started
    restart: yes
